Repository Daily-Step/challenge-server, pull requests merged in 2024-12, with the labels that each got.

#32 [Feat/30] 토큰 재발급 API 구현 및 테스트
  src/main/java/com/challenge/api/controller/auth/AuthController.java
  src/main/java/com/challenge/api/controller/auth/request/ReissueTokenRequest.java
  src/main/java/com/challenge/api/service/auth/AuthService.java
  src/main/java/com/challenge/api/service/auth/request/ReissueTokenServiceRequest.java
  src/main/java/com/challenge/api/service/auth/response/ReissueTokenResponse.java
  src/main/java/com/challenge/api/validator/auth/AuthValidator.java
  src/main/java/com/challenge/exception/ErrorCode.java
  src/main/java/com/challenge/utils/JwtUtil.java
  src/test/java/com/challenge/api/controller/auth/AuthControllerTest.java
  src/test/java/com/challenge/api/service/auth/AuthServiceTest.java
Labels: :sparkles: feature, ✅ test

#35 [Feat/34] 닉네임 중복 확인 API 구현 및 테스트
  src/main/java/com/challenge/api/controller/member/MemberController.java
  src/main/java/com/challenge/api/controller/member/request/CheckNicknameRequest.java
  src/main/java/com/challenge/api/service/member/MemberService.java
  src/main/java/com/challenge/api/service/member/request/CheckNicknameServiceRequest.java
  src/main/java/com/challenge/config/WebConfig.java
  src/test/java/com/challenge/api/controller/member/MemberControllerTest.java
  src/test/java/com/challenge/api/service/member/MemberServiceTest.java
Labels: :sparkles: feature, ✅ test

#36 [Feat/33] 내 회원 정보 조회 API 구현 및 테스트
  src/main/java/com/challenge/api/controller/member/MemberController.java
  src/main/java/com/challenge/api/service/member/MemberService.java
  src/main/java/com/challenge/api/service/member/response/MemberInfoResponse.java
  src/main/java/com/challenge/domain/job/Job.java
  src/test/java/com/challenge/api/controller/ControllerTestSupport.java
  src/test/java/com/challenge/api/controller/auth/AuthControllerTest.java
  src/test/java/com/challenge/api/controller/member/MemberControllerTest.java
  src/test/java/com/challenge/api/service/auth/AuthServiceTest.java
  src/test/java/com/challenge/api/service/member/MemberServiceTest.java
  src/test/java/com/challenge/domain/member/MemberRepositoryTest.java
Labels: :recycle: refactor, :sparkles: feature, ✅ test

#38 [Feat/37] 회원 정보 수정 API 구현 및 테스트
  src/main/java/com/challenge/api/controller/member/MemberController.java
  src/main/java/com/challenge/api/controller/member/request/UpdateBirthRequest.java
  src/main/java/com/challenge/api/controller/member/request/UpdateGenderRequest.java
  src/main/java/com/challenge/api/controller/member/request/UpdateJobRequest.java
  src/main/java/com/challenge/api/controller/member/request/UpdateJobYearRequest.java
  src/main/java/com/challenge/api/controller/member/request/UpdateNicknameRequest.java
  src/main/java/com/challenge/api/service/member/MemberService.java
  src/main/java/com/challenge/api/service/member/request/UpdateBirthServiceRequest.java
  src/main/java/com/challenge/api/service/member/request/UpdateGenderServiceRequest.java
  src/main/java/com/challenge/api/service/member/request/UpdateJobServiceRequest.java
  src/main/java/com/challenge/api/service/member/request/UpdateJobYearServiceRequest.java
  src/main/java/com/challenge/api/service/member/request/UpdateNicknameServiceRequest.java
  src/main/java/com/challenge/domain/member/Member.java
  src/test/java/com/challenge/api/controller/member/MemberControllerTest.java
  src/test/java/com/challenge/api/service/member/MemberServiceTest.java
Labels: :sparkles: feature, ✅ test

#41 [Feat/40] Swagger 설정 추가
  build.gradle
  src/main/java/com/challenge/config/SwaggerConfig.java
Labels: :sparkles: feature

#42 [Feat] 챌린지 추가 구현
  build.gradle
  src/docs/asciidoc/api/challenge/challenge-fail.adoc
  src/docs/asciidoc/api/challenge/challenge-success.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/challenge/api/controller/challenge/ChallengeController.java
  src/main/java/com/challenge/api/controller/challenge/request/ChallengeCreateRequest.java
  src/main/java/com/challenge/api/service/challenge/ChallengeService.java
  src/main/java/com/challenge/api/service/challenge/request/ChallengeCreateServiceRequest.java
  src/main/java/com/challenge/api/service/challenge/response/ChallengeResponse.java
  src/main/java/com/challenge/api/service/record/response/RecordResponse.java
  src/main/java/com/challenge/api/validator/CategoryValidator.java
  src/main/java/com/challenge/domain/category/Category.java
  src/main/java/com/challenge/domain/challenge/Challenge.java
  src/main/java/com/challenge/domain/challenge/ChallengeRepository.java
  src/main/java/com/challenge/domain/challenge/Record.java
  src/main/java/com/challenge/exception/ErrorCode.java
  src/main/java/com/challenge/utils/DateUtils.java
  src/test/java/com/challenge/api/controller/ControllerTestSupport.java
  src/test/java/com/challenge/api/controller/category/CategoryControllerTest.java
  src/test/java/com/challenge/api/controller/challenge/ChallengeControllerTest.java
  src/test/java/com/challenge/api/service/auth/AuthServiceTest.java
  src/test/java/com/challenge/api/service/category/CategoryServiceTest.java
  src/test/java/com/challenge/api/service/challenge/ChallengeServiceTest.java
  src/test/java/com/challenge/api/service/member/MemberServiceTest.java
  src/test/java/com/challenge/api/validator/CategoryValidatorTest.java
  src/test/java/com/challenge/docs/RestDocsSupport.java
  src/test/java/com/challenge/docs/challenge/ChallengeControllerDocsTest.java
  src/test/java/com/challenge/domain/challenge/ChallengeRepositoryTest.java
  src/test/java/com/challenge/domain/challenge/ChallengeTest.java
  src/test/java/com/challenge/domain/member/MemberRepositoryTest.java
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: :sparkles: feature

#45 [Fix/43] Swagger request에 member 제거 및 api http 메소드 변경
  src/main/java/com/challenge/annotation/AuthMember.java
  src/main/java/com/challenge/api/controller/member/MemberController.java
  src/test/java/com/challenge/api/controller/member/MemberControllerTest.java
Labels: :bug: bug

#46 [Feat] 챌린지 달성 및 테스트 구현
  build.gradle
  src/docs/asciidoc/api/challenge.adoc
  src/docs/asciidoc/api/challenge/challenge-fail.adoc
  src/docs/asciidoc/api/challenge/challenge-success.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/challenge/ChallengeApplication.java
  src/main/java/com/challenge/api/controller/challenge/ChallengeController.java
  src/main/java/com/challenge/api/service/auth/AuthService.java
  src/main/java/com/challenge/api/service/challenge/ChallengeService.java
  src/main/java/com/challenge/api/service/challenge/response/ChallengeResponse.java
  src/main/java/com/challenge/api/service/record/response/RecordResponse.java
  src/main/java/com/challenge/api/validator/AuthValidator.java
  src/main/java/com/challenge/api/validator/ChallengeValidator.java
  src/main/java/com/challenge/domain/challenge/Challenge.java
  src/main/java/com/challenge/domain/challenge/ChallengeQueryRepository.java
  src/main/java/com/challenge/domain/member/Member.java
  src/main/java/com/challenge/domain/record/Record.java
  src/main/java/com/challenge/domain/record/RecordRepository.java
  src/main/java/com/challenge/exception/ErrorCode.java
  src/main/java/com/challenge/utils/DateUtils.java
  src/test/java/com/challenge/api/controller/ControllerTestSupport.java
  src/test/java/com/challenge/api/controller/auth/AuthControllerTest.java
  src/test/java/com/challenge/api/controller/category/CategoryControllerTest.java
  src/test/java/com/challenge/api/controller/challenge/ChallengeControllerTest.java
  src/test/java/com/challenge/api/controller/member/MemberControllerTest.java
  src/test/java/com/challenge/api/service/auth/AuthServiceTest.java
  src/test/java/com/challenge/api/service/challenge/ChallengeServiceTest.java
  src/test/java/com/challenge/api/validator/ChallengeValidatorTest.java
  src/test/java/com/challenge/docs/RestDocsSupport.java
  src/test/java/com/challenge/docs/challenge/ChallengeControllerDocsTest.java
  src/test/java/com/challenge/domain/challenge/ChallengeQueryRepositoryTest.java
Labels: :sparkles: feature, ✅ test

#50 [Feat] 챌린지 달성 기능 수정
  Dockerfile
  src/main/java/com/challenge/api/controller/challenge/ChallengeController.java
  src/main/java/com/challenge/api/service/challenge/ChallengeService.java
  src/main/java/com/challenge/api/service/challenge/response/ChallengeResponse.java
  src/main/java/com/challenge/api/service/record/response/RecordResponse.java
  src/main/java/com/challenge/api/validator/ChallengeValidator.java
  src/main/java/com/challenge/domain/challenge/ChallengeQueryRepository.java
  src/main/java/com/challenge/domain/challenge/ChallengeRepository.java
  src/main/java/com/challenge/domain/record/Record.java
  src/main/java/com/challenge/domain/record/RecordStatus.java
  src/main/java/com/challenge/exception/ErrorCode.java
  src/main/java/com/challenge/exception/GlobalException.java
  src/main/java/com/challenge/utils/DateUtils.java
  src/main/java/com/challenge/utils/date/DateFormatter.java
  src/main/java/com/challenge/utils/date/DateUtils.java
  src/main/java/com/challenge/validator/DateValidator.java
  src/test/java/com/challenge/api/controller/challenge/ChallengeControllerTest.java
  src/test/java/com/challenge/api/service/challenge/ChallengeServiceTest.java
  src/test/java/com/challenge/api/validator/ChallengeValidatorTest.java
  src/test/java/com/challenge/docs/CategoryControllerDocsTest.java
  src/test/java/com/challenge/docs/ChallengeControllerDocsTest.java
  src/test/java/com/challenge/domain/challenge/ChallengeQueryRepositoryTest.java
  src/test/java/com/challenge/domain/challenge/ChallengeRepositoryTest.java
Labels: :recycle: refactor, :sparkles: feature

#51 [Docs] 카테고리 조회 문서 추가
  src/docs/asciidoc/api/category.adoc
  src/docs/asciidoc/api/challenge.adoc
  src/docs/asciidoc/index.adoc
  src/test/java/com/challenge/docs/CategoryControllerDocsTest.java
Labels: :memo: documentation

#53 [Feat/39] 회원 프로필 사진 등록 API 구현 및 테스트
  .github/workflows/github_actions.yml
  Dockerfile
  build.gradle
  src/main/java/com/challenge/api/controller/member/MemberController.java
  src/main/java/com/challenge/api/service/member/MemberService.java
  src/main/java/com/challenge/api/service/s3/S3ClientService.java
  src/main/java/com/challenge/config/S3ClientConfig.java
  src/main/java/com/challenge/domain/member/Member.java
  src/main/java/com/challenge/exception/ErrorCode.java
  src/main/resources/application.yml
  src/test/java/com/challenge/api/controller/member/MemberControllerTest.java
  src/test/java/com/challenge/api/service/auth/AuthServiceTest.java
  src/test/java/com/challenge/api/service/member/MemberServiceTest.java
  src/test/java/com/challenge/domain/member/MemberRepositoryTest.java
Labels: :recycle: refactor, :sparkles: feature, ✅ test

#55 [CI] 배포 에러 버그 수정
  .github/workflows/github_actions.yml
Labels: :construction_worker: ci

#56 [Feat] 챌린지 달성 취소 구현
  src/main/java/com/challenge/api/controller/challenge/ChallengeController.java
  src/main/java/com/challenge/api/service/challenge/ChallengeService.java
  src/main/java/com/challenge/api/validator/ChallengeValidator.java
  src/main/java/com/challenge/api/validator/RecordValidator.java
  src/main/java/com/challenge/domain/record/Record.java
  src/main/java/com/challenge/domain/record/RecordStatus.java
  src/main/java/com/challenge/exception/ErrorCode.java
  src/test/java/com/challenge/api/service/challenge/ChallengeServiceTest.java
  src/test/java/com/challenge/api/validator/ChallengeValidatorTest.java
  src/test/java/com/challenge/domain/challenge/ChallengeQueryRepositoryTest.java
Labels: :sparkles: feature

#58 [Feat] 챌린지 수정 구현
  src/main/java/com/challenge/api/controller/challenge/ChallengeController.java
  src/main/java/com/challenge/api/controller/challenge/request/ChallengeUpdateRequest.java
  src/main/java/com/challenge/api/service/challenge/ChallengeService.java
  src/main/java/com/challenge/api/service/challenge/request/ChallengeUpdateServiceRequest.java
  src/main/java/com/challenge/api/validator/CategoryValidator.java
  src/main/java/com/challenge/api/validator/ChallengeValidator.java
  src/main/java/com/challenge/domain/challenge/Challenge.java
  src/test/java/com/challenge/api/validator/CategoryValidatorTest.java
  src/test/java/com/challenge/api/validator/ChallengeValidatorTest.java
Labels: :sparkles: feature

#60 [Docs/47] 로그인, 회원 관련 API 문서 작성 및 rest docs 설정
  .gitignore
  src/docs/asciidoc/api/auth.adoc
  src/docs/asciidoc/api/category.adoc
  src/docs/asciidoc/api/challenge.adoc
  src/docs/asciidoc/api/member.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/challenge/api/controller/auth/request/KakaoSigninRequest.java
  src/main/java/com/challenge/api/controller/member/request/UpdateBirthRequest.java
  src/main/java/com/challenge/api/service/member/response/MemberInfoResponse.java
  src/main/java/com/challenge/validator/annotation/ValidDate.java
  src/main/java/com/challenge/validator/annotationValidator/ValidDateAnnotationValidator.java
  src/main/resources/application.yml
  src/test/java/com/challenge/api/controller/ControllerTestSupport.java
  src/test/java/com/challenge/api/controller/auth/AuthControllerTest.java
  src/test/java/com/challenge/api/controller/member/MemberControllerTest.java
  src/test/java/com/challenge/api/service/member/MemberServiceTest.java
  src/test/java/com/challenge/docs/AuthControllerDocsTest.java
  src/test/java/com/challenge/docs/MemberControllerDocsTest.java
  src/test/java/com/challenge/docs/RestDocsConfiguration.java
  src/test/java/com/challenge/docs/RestDocsSupport.java
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
Labels: :memo: documentation, :recycle: refactor

#61 [CI] 배포 에러 버그 수정
  src/main/resources/application.yml
Labels: :bug: bug, :construction_worker: ci

#62 [Feat] 챌린지 삭제 구현
  src/main/java/com/challenge/api/controller/challenge/ChallengeController.java
  src/main/java/com/challenge/api/service/challenge/ChallengeService.java
Labels: :sparkles: feature

#68 [Test] 챌린지 수정 테스트 및 문서화
  src/docs/asciidoc/api/auth.adoc
  src/docs/asciidoc/api/category.adoc
  src/docs/asciidoc/api/challenge.adoc
  src/docs/asciidoc/api/member.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/challenge/api/controller/challenge/ChallengeController.java
  src/main/java/com/challenge/api/controller/challenge/request/ChallengeAchieveRequest.java
  src/main/java/com/challenge/api/controller/challenge/request/ChallengeCancelRequest.java
  src/main/java/com/challenge/api/service/challenge/ChallengeService.java
  src/main/java/com/challenge/api/service/challenge/request/ChallengeAchieveServiceRequest.java
  src/main/java/com/challenge/api/service/challenge/request/ChallengeCancelServiceRequest.java
  src/main/java/com/challenge/api/validator/ChallengeValidator.java
  src/main/java/com/challenge/exception/ApiControllerAdvice.java
  src/main/resources/application.yml
  src/test/java/com/challenge/api/controller/ControllerTestSupport.java
  src/test/java/com/challenge/api/controller/challenge/ChallengeControllerTest.java
  src/test/java/com/challenge/api/controller/member/MemberControllerTest.java
  src/test/java/com/challenge/api/service/challenge/ChallengeServiceTest.java
  src/test/java/com/challenge/api/validator/ChallengeValidatorTest.java
  src/test/java/com/challenge/docs/AuthControllerDocsTest.java
  src/test/java/com/challenge/docs/ChallengeControllerDocsTest.java
  src/test/java/com/challenge/docs/MemberControllerDocsTest.java
  src/test/java/com/challenge/docs/RestDocsConfiguration.java
  src/test/java/com/challenge/docs/RestDocsSupport.java
  src/test/resources/org/springframework/restdocs/templates/path-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: :memo: documentation, :recycle: refactor, ✅ test

#70 [Test] 챌린지 삭제 테스트 및 문서화
  src/docs/asciidoc/api/challenge.adoc
  src/test/java/com/challenge/api/controller/challenge/ChallengeControllerTest.java
  src/test/java/com/challenge/api/service/challenge/ChallengeServiceTest.java
  src/test/java/com/challenge/docs/ChallengeControllerDocsTest.java
Labels: :memo: documentation, ✅ test

#72 [Feat] 챌린지 목록 조회 수정
  src/main/java/com/challenge/api/controller/challenge/ChallengeController.java
  src/main/java/com/challenge/api/controller/challenge/request/ChallengeQueryRequest.java
  src/main/java/com/challenge/api/service/challenge/ChallengeService.java
  src/main/java/com/challenge/api/service/challenge/request/ChallengeQueryServiceRequest.java
  src/main/java/com/challenge/domain/challenge/ChallengeQueryRepository.java
  src/test/java/com/challenge/api/controller/challenge/ChallengeControllerTest.java
  src/test/java/com/challenge/api/service/challenge/ChallengeServiceTest.java
  src/test/java/com/challenge/domain/challenge/ChallengeQueryRepositoryTest.java
Labels: :sparkles: feature, ✅ test

#74 [Feat/73] 프로필 사진 조회 API 구현
  src/main/java/com/challenge/api/controller/member/MemberController.java
  src/main/java/com/challenge/api/service/member/MemberService.java
  src/main/resources/application.yml
Labels: :sparkles: feature
