Repository Daily-Step/challenge-server, pull requests merged in 2024-11, with the labels that each got.

#4 feat: JPA 엔티티 생성 및 연관관계 매핑
  .gitignore
  build.gradle
  src/main/java/com/challenge/ChallengeApplication.java
  src/main/java/com/challenge/domain/.gitkeep
  src/main/java/com/challenge/domain/BaseDateTimeEntity.java
  src/main/java/com/challenge/domain/category/Category.java
  src/main/java/com/challenge/domain/challenge/Challenge.java
  src/main/java/com/challenge/domain/challenge/ChallengeMemo.java
  src/main/java/com/challenge/domain/challenge/ChallengeRecord.java
  src/main/java/com/challenge/domain/member/Member.java
  src/main/java/com/challenge/domain/notification/Notification.java
Labels: :sparkles: feature

#7 [Feat/5] 카카오 소셜 로그인 API 구현
  .editorconfig
  build.gradle
  src/main/java/com/challenge/ChallengeApplication.java
  src/main/java/com/challenge/api/controller/AuthController.java
  src/main/java/com/challenge/api/controller/SocialTestController.java
  src/main/java/com/challenge/api/dto/AuthRequest.java
  src/main/java/com/challenge/api/dto/AuthResponse.java
  src/main/java/com/challenge/api/service/.gitkeep
  src/main/java/com/challenge/api/service/AuthService.java
  src/main/java/com/challenge/api/service/KakaoApiService.java
  src/main/java/com/challenge/domain/BaseDateTimeEntity.java
  src/main/java/com/challenge/domain/category/Category.java
  src/main/java/com/challenge/domain/challenge/Challenge.java
  src/main/java/com/challenge/domain/challenge/ChallengeMemo.java
  src/main/java/com/challenge/domain/challenge/ChallengeRecord.java
  src/main/java/com/challenge/domain/member/LoginType.java
  src/main/java/com/challenge/domain/member/Member.java
  src/main/java/com/challenge/domain/member/MemberRepository.java
  src/main/java/com/challenge/domain/notification/Notification.java
  src/main/java/com/challenge/exception/ErrorCode.java
  src/main/java/com/challenge/utils/JwtUtil.java
  src/main/resources/application.yml
  src/main/resources/static/images/kakao_login_medium_narrow.png
  src/main/resources/templates/accessToken.html
  src/main/resources/templates/login.html
Labels: :sparkles: feature

#9 [Feat/8] 로컬->RDS ssh 접속 설정
  build.gradle
  src/main/java/com/challenge/config/.gitkeep
  src/main/java/com/challenge/config/SshDataSourceConfig.java
  src/main/java/com/challenge/config/SshTunnelingInitializer.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#11 [Feat/6] CI/CD 파이프라인 구축
  .github/workflows/github_actions.yml
  Dockerfile
  build.gradle
  src/main/java/com/challenge/api/controller/HomeController.java
  src/main/java/com/challenge/api/controller/TestController.java
  src/main/java/com/challenge/config/SshTunnelingInitializer.java
  src/main/resources/application.yml
  src/test/java/com/challenge/ChallengeApplicationTests.java
Labels: :construction_worker: ci

#12 [Feat/6] CI/CD 트리거 변경
  .github/workflows/github_actions.yml
Labels: :construction_worker: ci

#13 [Feat/6] CI/CD 트리거 branch 이름 변경
  .github/workflows/github_actions.yml
Labels: :construction_worker: ci

#17 [Feat 15] 기획 변경에 따른 챌린지 및 기록 엔티티 변경
  src/main/java/com/challenge/domain/category/Category.java
  src/main/java/com/challenge/domain/challenge/Challenge.java
  src/main/java/com/challenge/domain/challenge/ChallengeRecord.java
  src/main/java/com/challenge/domain/challenge/Record.java
Labels: :sparkles: feature

#22 [Feat] 카테고리 목록 조회 구현
  src/main/java/com/challenge/api/controller/category/CategoryController.java
  src/main/java/com/challenge/api/service/category/CategoryService.java
  src/main/java/com/challenge/api/service/category/response/CategoryResponse.java
  src/main/java/com/challenge/domain/category/Category.java
  src/main/java/com/challenge/domain/category/CategoryRepository.java
Labels: :sparkles: feature

#25 [Feat/10] 카카오 소셜 로그인/회원가입 API 구현
  src/main/java/com/challenge/api/controller/AuthController.java
  src/main/java/com/challenge/api/controller/auth/AuthController.java
  src/main/java/com/challenge/api/controller/auth/SocialTestController.java
  src/main/java/com/challenge/api/controller/auth/request/KakaoLoginRequest.java
  src/main/java/com/challenge/api/controller/auth/request/KakaoSigninRequest.java
  src/main/java/com/challenge/api/dto/AuthRequest.java
  src/main/java/com/challenge/api/dto/AuthResponse.java
  src/main/java/com/challenge/api/service/AuthService.java
  src/main/java/com/challenge/api/service/auth/AuthService.java
  src/main/java/com/challenge/api/service/auth/KakaoApiService.java
  src/main/java/com/challenge/api/service/auth/request/KakaoLoginServiceRequest.java
  src/main/java/com/challenge/api/service/auth/request/KakaoSigninServiceRequest.java
  src/main/java/com/challenge/api/service/auth/response/LoginResponse.java
  src/main/java/com/challenge/api/service/auth/response/SocialInfoResponse.java
  src/main/java/com/challenge/api/validator/auth/AuthValidator.java
  src/main/java/com/challenge/domain/BaseDateTimeEntity.java
  src/main/java/com/challenge/domain/job/Job.java
  src/main/java/com/challenge/domain/job/JobRepository.java
  src/main/java/com/challenge/domain/member/Gender.java
  src/main/java/com/challenge/domain/member/Member.java
  src/main/java/com/challenge/domain/member/MemberRepository.java
  src/main/java/com/challenge/domain/member/Year.java
  src/main/java/com/challenge/domain/notification/Notification.java
  src/main/java/com/challenge/exception/ErrorCode.java
  src/main/java/com/challenge/utils/JwtUtil.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#28 [Feat/27] JWT 검증 인터셉터 및 커스텀 어노테이션 구현
  src/main/java/com/challenge/annotation/AuthMember.java
  src/main/java/com/challenge/annotation/resolver/AuthMemberArgumentResolver.java
  src/main/java/com/challenge/api/interceptor/AuthInterceptor.java
  src/main/java/com/challenge/config/WebConfig.java
  src/main/java/com/challenge/exception/ErrorCode.java
  src/main/java/com/challenge/utils/JwtUtil.java
Labels: :sparkles: feature

#31 [Test/29] 카카오 로그인/회원가입 API 테스트코드 작성
  src/main/java/com/challenge/api/controller/auth/request/KakaoLoginRequest.java
  src/main/java/com/challenge/api/controller/auth/request/KakaoSigninRequest.java
  src/main/java/com/challenge/api/service/auth/AuthService.java
  src/main/java/com/challenge/domain/job/Job.java
  src/main/java/com/challenge/domain/member/JobYear.java
  src/main/java/com/challenge/domain/member/Member.java
  src/test/java/com/challenge/api/controller/ControllerTestSupport.java
  src/test/java/com/challenge/api/controller/auth/AuthControllerTest.java
  src/test/java/com/challenge/api/controller/category/CategoryControllerTest.java
  src/test/java/com/challenge/api/service/auth/AuthServiceTest.java
Labels: :recycle: refactor, ✅ test
