Repository Daily-Step/challenge-server, pull requests merged in 2025-01, with the labels that each got.

#77 fix: 챌린지 생성시 카테고리아이디가 null로 들어오는 버그 수정
  src/main/java/com/challenge/api/controller/challenge/request/ChallengeCreateRequest.java
  src/test/java/com/challenge/api/service/challenge/ChallengeServiceTest.java
Labels: :bug: bug

#78 [Docs] 챌린지 조회 문서 작성
  src/main/java/com/challenge/api/controller/challenge/request/ChallengeQueryRequest.java
  src/test/java/com/challenge/docs/ChallengeControllerDocsTest.java
Labels: :memo: documentation

#80 [Docs] 챌린지 조회 문서 수정
  src/docs/asciidoc/api/challenge.adoc
  src/test/java/com/challenge/docs/ChallengeControllerDocsTest.java
Labels: :memo: documentation

#82 [Docs] 챌린지 달성 취소 문서 작성
  Dockerfile
  src/docs/asciidoc/api/challenge.adoc
  src/main/java/com/challenge/api/controller/challenge/ChallengeController.java
  src/main/java/com/challenge/api/controller/challenge/request/ChallengeUpdateRequest.java
Labels: :memo: documentation

#83 [Feat/66] FCM 알림 전송 구현 및 테스트 API 구현
  .github/workflows/github_actions.yml
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/com/challenge/api/controller/fcm/FcmController.java
  src/main/java/com/challenge/api/controller/fcm/request/FcmSendByIdRequest.java
  src/main/java/com/challenge/api/controller/fcm/request/FcmSendByTokenRequest.java
  src/main/java/com/challenge/api/controller/fcm/request/TokenSaveRequest.java
  src/main/java/com/challenge/api/service/fcm/FcmService.java
  src/main/java/com/challenge/api/service/fcm/request/FcmMessage.java
  src/main/java/com/challenge/api/service/fcm/request/TokenSaveServiceRequest.java
  src/main/java/com/challenge/config/FcmConfig.java
  src/main/java/com/challenge/config/WebConfig.java
  src/main/java/com/challenge/domain/member/Member.java
  src/main/java/com/challenge/domain/notification/Notification.java
  src/main/java/com/challenge/domain/notification/NotificationRepository.java
  src/main/java/com/challenge/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#85 [Docs] 챌린지 달성 취소 문서 수정
  src/docs/asciidoc/api/challenge.adoc
  src/test/java/com/challenge/docs/ChallengeControllerDocsTest.java
Labels: :memo: documentation

#86 [Feat/66] firebase json 파일 관련 배포 문제 해결
  .github/workflows/github_actions.yml
  src/main/resources/application.yml
Labels: :bug: bug, :construction_worker: ci

#89 [Fix] 챌린지 달성 취소 버그 수정
  src/main/java/com/challenge/api/controller/challenge/request/ChallengeCancelRequest.java
  src/main/java/com/challenge/api/service/challenge/ChallengeService.java
  src/main/java/com/challenge/domain/challenge/Challenge.java
  src/test/java/com/challenge/api/service/challenge/ChallengeServiceTest.java
Labels: :bug: bug, :sparkles: feature

#92 [Fix] 챌린지 삭제 버그 수정
  src/main/java/com/challenge/api/service/challenge/ChallengeService.java
  src/main/java/com/challenge/domain/challenge/Challenge.java
  src/main/java/com/challenge/domain/challenge/ChallengeQueryRepository.java
  src/test/java/com/challenge/api/service/challenge/ChallengeServiceTest.java
Labels: :bug: bug, :sparkles: feature

#94 [Fix/93] 직무, 연차 정보 선택 안함 옵션 가능하도록 수정
  src/main/java/com/challenge/api/controller/auth/request/KakaoSigninRequest.java
  src/main/java/com/challenge/api/controller/member/request/UpdateJobRequest.java
  src/main/java/com/challenge/api/controller/member/request/UpdateJobYearRequest.java
  src/main/java/com/challenge/api/service/auth/AuthService.java
  src/main/java/com/challenge/api/service/member/MemberService.java
  src/main/java/com/challenge/api/service/member/response/MemberInfoResponse.java
  src/main/java/com/challenge/domain/member/Member.java
  src/test/java/com/challenge/api/controller/auth/AuthControllerTest.java
  src/test/java/com/challenge/api/controller/member/MemberControllerTest.java
  src/test/java/com/challenge/docs/AuthControllerDocsTest.java
  src/test/java/com/challenge/docs/MemberControllerDocsTest.java
Labels: :bug: bug

#95 [WIP] 챌린지 현황 API 진행 중
  src/main/java/com/challenge/api/service/challenge/ChallengeService.java
  src/main/java/com/challenge/api/service/record/response/RecordResponse.java
  src/main/java/com/challenge/api/validator/RecordValidator.java
  src/main/java/com/challenge/domain/challenge/ChallengeQueryRepository.java
  src/main/java/com/challenge/domain/challenge/ChallengeRepository.java
  src/main/java/com/challenge/domain/record/Record.java
  src/test/java/com/challenge/api/validator/ChallengeValidatorTest.java
  src/test/java/com/challenge/domain/challenge/ChallengeQueryRepositoryTest.java
Labels: :sparkles: feature

#100 [Feat] 챌린지 현황 조회 (#99)
  src/main/java/com/challenge/api/service/challenge/response/ChallengeResponse.java
  src/main/java/com/challenge/domain/challenge/Challenge.java
  src/main/java/com/challenge/domain/challenge/ChallengeQueryRepository.java
  src/main/java/com/challenge/domain/challenge/ChallengeStatus.java
  src/test/java/com/challenge/api/service/challenge/ChallengeServiceTest.java
  src/test/java/com/challenge/api/validator/RecordValidatorTest.java
  src/test/java/com/challenge/docs/ChallengeControllerDocsTest.java
  src/test/java/com/challenge/domain/challenge/ChallengeQueryRepositoryTest.java
  src/test/java/com/challenge/domain/challengeRecord/ChallengeRecordQueryRepositoryTest.java
Labels: :sparkles: feature

#102 [Feat/87] 알림 발송 스케줄러 및 알림 내역 저장 기능 구현
  src/main/java/com/challenge/api/service/notification/AchieveChallengeDTO.java
  src/main/java/com/challenge/api/service/notification/NewChallengeDTO.java
  src/main/java/com/challenge/api/service/notification/NotificationService.java
  src/main/java/com/challenge/config/SchedulerConfig.java
  src/main/java/com/challenge/domain/notification/NotificationQueryRepository.java
  src/main/java/com/challenge/scheduler/NotificationScheduler.java
  src/test/java/com/challenge/domain/notification/NotificationQueryRepositoryTest.java
Labels: :sparkles: feature, ✅ test

#104 [Feat/103] 회원 마이페이지 조회 API 구현
  src/main/java/com/challenge/api/controller/member/MemberController.java
  src/main/java/com/challenge/api/service/member/MemberService.java
  src/main/java/com/challenge/api/service/member/response/MyPageResponse.java
  src/main/java/com/challenge/scheduler/NotificationScheduler.java
Labels: :sparkles: feature

#107 [Feat/106] 마이페이지 조회 API 응답 값 추가
  src/main/java/com/challenge/api/service/member/response/MyPageResponse.java
Labels: :sparkles: feature

#108 [Feat/101] 챌린지 스케줄러 구현
  src/main/java/com/challenge/api/service/challenge/ChallengeService.java
  src/main/java/com/challenge/config/ClockConfig.java
  src/main/java/com/challenge/domain/challenge/Challenge.java
  src/main/java/com/challenge/domain/challenge/ChallengeQueryRepository.java
  src/main/java/com/challenge/domain/challengeRecord/ChallengeRecordRepository.java
  src/main/java/com/challenge/scheduler/ChallengeScheduler.java
  src/test/java/com/challenge/domain/challenge/ChallengeQueryRepositoryTest.java
  src/test/java/com/challenge/domain/challengeRecord/ChallengeRecordRepositoryTest.java
  src/test/java/com/challenge/scheduler/ChallengeSchedulerTest.java
Labels: :sparkles: feature, ✅ test

#110 [Feat] 미래 날짜 달성 및 취소 기능 구현
  src/main/java/com/challenge/api/service/challenge/ChallengeService.java
Labels: :sparkles: feature
